- {
  version: 1.14.5.14,
  data:
    [ 
      什么？插件报错？？？你看看<span class="cmd">BTC-？？？？-plugin</span>，一看就是<span class="cmd">MEMZ</span>干的
      修复<span class="cmd">bug</span>,
      增加<span class="cmd">特性</span>,
      优化<span class="cmd">代码</span>,
      <span class="cmd">枫林&枫叶&MEMZ</span>干的,
      优化bug 增加特性,
      优化<span class="cmd">帮助</span>代码, 
    ],
}